from typing import Tuple
from cv2.typing import MatLike
from cv2 import UMat
from PIL.Image import Image

def read_image_as_bgr(filename:str) -> MatLike:...
def read_image_as_gray(filename:str) -> MatLike:...
def read_image_as_rgb(filename:str) -> MatLike:...
def get_width_and_heigt(img:MatLike) -> Tuple[int,int,int]:...
def convert_from_bgr_to_rgb(img_bgr) -> MatLike|UMat:...
def get_image_as_rgb(filename:str) -> Image:...